exports.create = {
	Person: [
		{
			'name.full': 'Jed Watson',
			email: 'jed@thinkmill.com.au',
			password: 'admin',
			company: 'Thinkmill',
			github: 'JedWatson',
			twitter: 'JedWatson',
			homepage: 'http://thinkmill.com.au',
			isAdmin: true,
			__ref: 'jed',
		},
		{
			'name.full': 'Christopher Chedeau',
			email: 'vjeux@fb.com',
			password: 'admin',
			company: 'Facebook',
			github: 'vjeux',
			twitter: 'vjeux',
			homepage: 'http://blog.vjeux.com',
			isAdmin: true,
			__ref: 'vjeux',
		},
		{
			'name.full': 'Brent Vatne',
			email: 'brentvatne@gmail.com',
			password: 'admin',
			company: 'Exponent',
			github: 'brentvatne',
			twitter: 'notbrent',
			homepage: 'http://brentvatne.ca',
			isAdmin: true,
			__ref: 'brent',
		},
		{
			'name.full': 'Adam Miskiewicz',
			email: 'adam@adammiskiewicz.com',
			password: 'admin',
			company: 'Chalk + Chisel',
			github: 'skevy',
			twitter: 'skevy',
			homepage: 'http://www.adammiskiewicz.com/',
			isAdmin: true,
			__ref: 'skevy',
		},
	],
};
